// ===============================================================================
// 14-CLAUSES-COMPLETES.TS — Texte integral des clauses contractuelles
// ===============================================================================

import { KnowledgeChunk } from './types';

export const clausesCompletesChunks: KnowledgeChunk[] = [
  // ---------------------------------------------------------------------------
  // CLAUSE 2 — GRANT OF LICENSE
  // ---------------------------------------------------------------------------
  {
    id: "clause-2-license",
    category: "clauses",
    title: "Clause 2 — Grant of License (Texte integral)",
    content: `CLAUSE 2 — GRANT OF LICENSE ON THE LICENSED CONTENT AND DEVELOPMENT OF NEW CONTENT

CLAUSE 2.1 — Grant of License:
Licensor hereby grants to Licensee, with effect from the License Effective Date, License to use the Licensed IP for the License Period, subject always to the other terms of this Agreement.

CLAUSE 2.3 — Restrictions on Licensor:
(a) Licensor is not entitled to dispose, sell, transfer, assign or license the Licensed Content to any other third parties during the License Period without Licensee's prior written consent;
(b) Licensor does not have the right to prevent Licensee from accessing to data/accounts;
(c) Licensor warrants that it owns the Licensed Content and Licensed IP free from any claims or encumbrances and is entitled to grant the rights granted under this Agreement.

CLAUSE 2.5 — Content Creation Obligation:
Licensor undertakes:
(i) not to intentionally refrain from creating New Content or generating Rights Payments; and
(ii) not to take any action that would change its ability to generate Rights Payments by positive action or omission, with the purpose or intent of avoiding its obligations under this Agreement.

IMPORTANT: For the avoidance of doubt, breach of this Clause shall be a breach of this Agreement within the meaning of Clause 7.1 (Breach Call Option).

APPLICATION AU CAS ADN:
La perte de la page Oye (piratage) n'est PAS une violation de la Clause 2.5 car:
- ADN n'a pas "intentionnellement" perdu la page
- ADN n'avait pas le controle du Business Manager
- CC etait le gardien technique exclusif`,
    keywords: ["clause 2", "license", "grant", "content", "creation", "obligation"]
  },

  // ---------------------------------------------------------------------------
  // CLAUSE 4 — PAYMENT (Texte complet)
  // ---------------------------------------------------------------------------
  {
    id: "clause-4-payment-complet",
    category: "clauses",
    title: "Clause 4 — Payment (Texte integral)",
    content: `CLAUSE 4 — PAYMENT

CLAUSE 4.1 — Revenue Share:
(a) Licensor agrees to pay to Licensee the Revenue Share generated by the Licensed Content and New Content in accordance with the terms of this Agreement.
(b) Licensor appoints Licensee to collect Rights Payments on its behalf.

CLAUSE 4.2 — Deposit of Rights Payments:
Licensor agrees to enter into an authorization agreement ("Authorization Agreement") under which Licensor authorizes Licensee to access Licensor's Connected Accounts in order to collect Rights Payments.

CLAUSE 4.3 — Payment Mechanics:
(a) Licensee shall be entitled to retain Revenue Share directly from Rights Payments.
(b) Until such time when Licensee fully receives the Specified Amount, within the first week of each month, Licensee will inform Licensor by email of the amount of Rights Payments generated during the previous month.
(c) At least once per month, Licensee will debit from the Connected Accounts an amount which corresponds to the Revenue Share already generated.
(d) Licensor is solely responsible for any fees or charges incurred from overdrafts or rejected transactions. In case bounce charges start occurring regularly (more than 2 times in 6 months), Clause 6 (Liquidated Damages) shall apply.

CLAUSE 4.3(e)(ii) — EXCEPTION AUX PENALITES (DEFENSE ADN):
"Provided Licensor is without fault in causing such default or delay, and such default or delay could not have been prevented by reasonable precautions and could not reasonably be circumvented by Licensor using alternate sources, workaround plans or other means, then the penalty for late payment shall not apply."

IMPORTANCE STRATEGIQUE:
Cette clause est CRUCIALE pour la defense d'ADN. Elle exonere ADN des penalites SI:
1. ADN est "without fault" (sans faute)
2. Le defaut "could not have been prevented" (ne pouvait pas etre evite)

ARGUMENT ADN:
- ADN n'avait pas le controle du Business Manager
- ADN n'avait pas acces au 2FA
- ADN ne pouvait pas empecher le piratage
- Donc ADN est "without fault" et le defaut "could not have been prevented"`,
    keywords: ["clause 4", "payment", "revenue", "share", "exception", "penalites", "without fault"]
  },

  // ---------------------------------------------------------------------------
  // CLAUSE 6 — LIQUIDATED DAMAGES (Texte complet)
  // ---------------------------------------------------------------------------
  {
    id: "clause-6-liquidated-damages-complet",
    category: "clauses",
    title: "Clause 6 — Liquidated Damages (Texte integral)",
    content: `CLAUSE 6 — LIQUIDATED DAMAGES (TEXTE INTEGRAL)

Si, en plus de tout autre recours et demande d'execution specifique de Licensee:

(a) Licensor, directement ou indirectement, ne paie pas un montant du a Licensee en totalite et a temps,
(b) Licensee n'a recu aucun paiement pendant 3 mois, ou
(c) moins de 20% du Specified Amount dans les 6 mois suivant la Closing Date,
(d) Licensee a recu moins de 50% du Specified Amount dans les 2 ans suivant la Closing Date, et/ou
(e) Licensor viole l'une de ses obligations selon les Clauses 2.6, 2.7, 4, 7 et 8 et cette violation reste non corrigee dans les 30 jours suivant la notification de Licensee,

ALORS:
(i) si la violation est une violation des engagements de la Clause 2.7(a), un montant egal a 2 FOIS le Specified Amount devient exigible
(ii) pour toute autre violation, un montant egal a 3 FOIS le Specified Amount devient exigible

CALCUL IMPACT:
| Violation | Multiplicateur | Montant |
|-----------|----------------|---------|
| Clause 2.7(a) | x2 | 420 000 EUR |
| Autres violations | x3 | 630 000 EUR |

DELAI DE PAIEMENT:
Le Licensor doit payer le Shortfall a Licensee dans les 5 jours suivant l'expiration du delai de remede de 30 jours.

DEFENSE ADN — CLAUSE 4.3(e)(ii):
L'exception "without fault" s'applique ici aussi. Si ADN peut demontrer qu'elle n'est pas en faute (controle exclusif de CC, pas d'acces au 2FA), les Liquidated Damages ne s'appliquent PAS.

DEFENSE ADN — ART. 163 CO SUISSE:
Les clauses penales manifestement excessives peuvent etre reduites par le juge selon l'Art. 163 CO. Un multiplicateur x3 pour un prejudice cause par CC pourrait etre considere comme excessif.`,
    keywords: ["clause 6", "liquidated", "damages", "penalites", "multiplicateur", "420000", "630000"]
  },

  // ---------------------------------------------------------------------------
  // CLAUSE 7 — BREACH CALL OPTION (Texte complet)
  // ---------------------------------------------------------------------------
  {
    id: "clause-7-breach-call-complet",
    category: "clauses",
    title: "Clause 7 — Breach Call Option (Texte integral)",
    content: `CLAUSE 7 — BREACH CALL OPTION (TEXTE INTEGRAL)

CLAUSE 7.1 — Conditions de declenchement:
During the Term of this Agreement ("Breach Option Period"), in each case:
(a) Licensor commits a breach of this Agreement (including the breach of any obligations under Clause 2 and 4) which breach is irremediable or, if remediable, is not remedied within 30 days after service of notice requiring the same;
(b) Licensor fails to pay the Shortfall to Licensee within 5-days period pursuant to Clause 6 (Liquidated Damages);
(c) Licensor has changed or removed Licensee's access to the Connected Accounts, without Licensee's advance written consent.

THEN Licensee shall be entitled to serve a Breach Call Notice to Licensor.

CLAUSE 7.2 — Breach Call Notice:
"During the Term of this Agreement, Licensee may give written notice to Licensor specifying that it wishes to acquire all or part of, to be chosen by Licensee, the Called Intellectual Property Rights for USD1 (one US dollar) ('Breach Call Notice')."

CLAUSE 7.3 — Effect of Breach Call Notice:
If Breach Call Notice is received within the Breach Option Period, Licensor shall grant to Licensee, with effect from the date of the Breach Call Notice, a world-wide, exclusive assignable, sub-licensable license to use the Called Intellectual Property Rights for an indefinite term.

CLAUSE 7.4 — Implementation:
Licensor shall take all actions necessary to the granting of the Called Intellectual Property Rights within 15 days following the Breach Call Notice, including executing a license agreement to that effect and take all actions to duly register the Called Intellectual Property Rights in the name of Licensee before the relevant registries.

DANGER MAXIMUM:
CC peut acquerir TOUTE la propriete intellectuelle d'ADN (pages, chaines, contenus) pour 1 USD.

DEFENSE ADN — ART. 2 CC (Abus de droit):
L'Art. 2 al. 2 du Code Civil suisse dispose: "L'abus manifeste d'un droit n'est pas protege par la loi."

ARGUMENT: Activer la Clause 7 pour recuperer 142 000 EUR alors que CC a cause 750 000 EUR+ de prejudice serait un abus de droit manifeste. La clause ne peut pas etre utilisee pour s'enrichir d'actifs valant des centaines de milliers d'euros a cause d'une dette de 142 000 EUR causee par la faute du creancier lui-meme.

ATF 143 III 1: Les clauses penales disproportionnees peuvent etre reduites ou annulees.`,
    keywords: ["clause 7", "breach", "call", "option", "1 dollar", "usd", "ip", "propriete intellectuelle", "abus droit"]
  },

  // ---------------------------------------------------------------------------
  // CLAUSE 9 — LIABILITY (Texte complet)
  // ---------------------------------------------------------------------------
  {
    id: "clause-9-liability-complet",
    category: "clauses",
    title: "Clause 9 — Liability (Texte integral)",
    content: `CLAUSE 9 — LIABILITY (TEXTE INTEGRAL)

CLAUSE 9.1 — Licensor's Indemnification:
Licensor shall indemnify, defend and hold harmless Licensee and its Group Companies and each of their respective directors, officers, employees, and agents for any loss, liability and cost, including reasonable attorneys' and expert's fees arising from or in connection with any allegation, claim or proceeding raised by a third party and any statutory or regulatory fines made against Licensee arising out of use of the Licensed Content in accordance with the Agreement or resulting from Licensor's breach of Applicable Law.

CLAUSE 9.2 — Limitation of Licensee's Liability:
"Licensee shall not be liable for any special, exemplary, consequential, incidental or indirect damages, regardless of the form of any claim or action, arising out of or in connection with this Agreement.

In any case, Licensee's total liability arising from this Agreement shall not exceed the Price paid by Licensor to Licensee under this Agreement."

PLAFOND: 150 000 EUR (le montant de l'avance recue)

CLAUSE 9.3 — Exceptions:
Nothing in this Clause 9 shall exclude or limit a party's liability to the other party:
(i) for fraud,
(ii) for death or personal injury caused by its negligence, or
(iii) to the extent the same may not be excluded or limited as a matter of law.

DEFENSE ADN — ART. 100 CO SUISSE:
"Est nulle toute stipulation tendant a liberer d'avance le debiteur de la responsabilite qu'il encourrait en cas de dol ou de faute grave."

APPLICATION:
Si ADN peut demontrer une FAUTE GRAVE de CC, la limitation de responsabilite (150 000 EUR) est ANNULEE. CC serait alors responsable de l'integralite du prejudice.

ELEMENTS DE FAUTE GRAVE:
1. Utilisation de Gmail personnels pour gerer des actifs de 1M EUR+
2. 2FA non actif malgre la recommandation de Meta
3. 4+ mois d'inaction totale apres le piratage
4. Oye = seule page piratee du portefeuille CC
5. Aucune enquete interne documentee`,
    keywords: ["clause 9", "liability", "responsabilite", "limitation", "150000", "plafond", "faute grave", "art 100"]
  },

  // ---------------------------------------------------------------------------
  // CONDITIONS PRECEDENTS (Purchase Order)
  // ---------------------------------------------------------------------------
  {
    id: "conditions-precedents-texte",
    category: "clauses",
    title: "Conditions Precedents — Super Admin (Texte integral)",
    content: `CONDITIONS PRECEDENTS — PURCHASE ORDER (TEXTE INTEGRAL)

"The followings shall be conditions precedent to the payment of Price. If not, the Price shall not be paid:"

CONDITION 1 — Super Admin Access:
"The Licensor shall provide and maintain the Licensee with an administrative access to the Platform Channels belonging to the Licensor, revokable only by the Licensee, allowing solely the Licensee to adjust payment settings to collect revenues on behalf of the Licensor.

In particular, the Licensor shall appoint the Licensee as super-administrator ('Super Admin') of the Facebook Channels listed above.

It is agreed that such administrative access should not be used by the Licensee to comment, edit or post contents."

CONDITION 2 — Integration into CC's Management Tools:
"The Licensor's Platform Channels listed above shall become and remain part of the intellectual property and copyright management tools of the Licensee.

In particular, the Licensor's YouTube Channels listed above shall become and remain part of the multi-channel network owned or controlled by the Licensee on YouTube, and the Licensor's Facebook Channels listed above shall become and remain part of the Facebook Rights Manager tool of the Licensee."

ANALYSE STRATEGIQUE:

| Ce que le contrat dit | Implication |
|-----------------------|-------------|
| CC "shall provide and maintain" l'acces | CC a une OBLIGATION de garde |
| "revokable only by the Licensee" | CC a le controle EXCLUSIF |
| Pages "shall become and remain part of" leurs outils | CC a une obligation de PRESERVATION |
| CC est "super-administrator" | CC a le POUVOIR MAXIMUM |

CONTRADICTION AVEC LA LETTRE CC 26/12:
CC pretend: "Technical administrative access does not equate to custodial or fiduciary responsibility"
LE CONTRAT DIT: CC doit "maintain" l'acces et les pages doivent "remain part of" leurs outils

CONCLUSION: Le contrat impose a CC une responsabilite de garde (custodial). Leur argument du 26/12 est contredit par leur propre contrat.`,
    keywords: ["conditions", "precedents", "super admin", "maintain", "remain", "custodial", "garde", "obligation"]
  },

  // ---------------------------------------------------------------------------
  // AMENDMENT PROTOCOL — Garantie personnelle
  // ---------------------------------------------------------------------------
  {
    id: "amendment-garantie-texte",
    category: "clauses",
    title: "Amendment Protocol — Garantie personnelle (Texte integral)",
    content: `AMENDMENT PROTOCOL — GARANTIE PERSONNELLE (TEXTE INTEGRAL)

Date de signature: 2 octobre 2024

MINIMUM MONTHLY PAYMENT:
"The Licensor and the Licensee agree that in the event that the monthly Share falls below EUR 6,000 (Six Thousand Euros), the Licensor is obligated to make a minimum payment of EUR 6,000 (Six Thousand Euros).

This amendment shall apply to both the first Production Advance solution with the Price of EUR 150,000 and the Second Production Advance solution with the Price of EUR 200,000."

PERSONAL GUARANTEE (Alexandre Quilghini):
"I, Alexandre Quilghini, the undersigned, having thoroughly understood the terms of this Amendment Protocol, the PO, and the Content License and Development Agreement dated September 26, 2024 ('License Agreement'), which was executed between the Licensee and Licensor, hereby irrevocably and personally guarantee the immediate and full payment of the minimum monthly payment of EUR 6,000 (Six Thousand Euros) as specified above.

My obligation under this personal guarantee shall take precedence over any other obligations or liabilities I may have, and I agree that my liability hereunder shall be fulfilled first and foremost, prior to the satisfaction of any other obligations."

PORTEE DE LA GARANTIE:

| Ce que la garantie COUVRE | Ce que la garantie NE COUVRE PAS |
|---------------------------|----------------------------------|
| Minimum mensuel de 6 000 EUR | Dette totale (142 000 EUR) |
| | Liquidated Damages (x3 = 630 000 EUR) |
| | Breach Call Option |
| | Interets et penalites additionnelles |

INTERPRETATION CC (Lettre 26/12):
CC pretend que la garantie est "personal, unconditional, and independent" couvrant TOUT.

REALITE:
Le texte ne mentionne que "the minimum monthly payment of EUR 6,000". L'interpretation extensive de CC n'est pas supportee par le texte.

SIGNATAIRES:
- Alexandre Quilghini (Licensor) — 02-Oct-24 13:50:10 CEST
- Jack Ojalvo (Licensee) — 02-Oct-24 16:10:24 CEST
- Alexandre Quilghini (Guarantor) — 02-Oct-24 13:50:10 CEST`,
    keywords: ["amendment", "garantie", "personnelle", "alex", "6000", "minimum", "mensuel"]
  },

  // ---------------------------------------------------------------------------
  // CLAUSE 14 — ARBITRATION (Texte complet)
  // ---------------------------------------------------------------------------
  {
    id: "clause-14-arbitration-complet",
    category: "clauses",
    title: "Clause 14 — Arbitration ICC (Texte integral)",
    content: `CLAUSE 14 — LAW, JURISDICTION AND DISPUTES (TEXTE INTEGRAL)

CLAUSE 14.1 — Governing Law:
"This Agreement shall be governed by and construed in accordance with the laws of Switzerland."

CLAUSE 14.2 — Arbitration:
"Any dispute arising out of or in connection with this Agreement, including any question regarding its existence, validity or termination, shall be referred to and finally resolved by arbitration under the ICC Arbitration Rules, which Rules are deemed to be incorporated by reference into this Clause."

CLAUSE 14.3 — Number of Arbitrators:
"The number of arbitrators will be 3 (three)."

CLAUSE 14.4 — Nomination:
"The claimant and the respondent shall each nominate 1 (one) member of the tribunal."

CLAUSE 14.5 — Emergency Arbitrator:
"The parties confirm that they opt out of the emergency arbitrator provisions."

CLAUSE 14.6 — Seat of Arbitration:
"The seat, or legal place, of arbitration will be Geneva, Switzerland."

CLAUSE 14.7 — Language:
"The language to be used in the arbitral proceedings will be English."

CLAUSE 14.8 — Costs:
"All expenses in relation to the arbitration proceedings, inclusive of the reasonable attorney fees, shall be borne by the party failing in such proceedings. Where parties partially prevail, the said expenses shall be apportioned between them according to the degree to which they prevailed."

RESUME:
| Element | Valeur |
|---------|--------|
| Droit applicable | Suisse |
| Reglement | ICC (Chambre de Commerce Internationale) |
| Nombre d'arbitres | 3 |
| Siege | Geneve, Suisse |
| Langue | Anglais |
| Opt-out Emergency Arbitrator | Oui |

COUT ESTIME D'UN ARBITRAGE ICC:
- Frais administratifs ICC: 15 000 - 50 000 EUR
- Honoraires des 3 arbitres: 50 000 - 150 000 EUR
- Avocats (chaque partie): 30 000 - 100 000 EUR
- TOTAL: 80 000 a 300 000 EUR

ARGUMENT STRATEGIQUE:
CC devrait depenser 100 000 - 300 000 EUR en arbitrage pour recuperer 142 000 EUR de dette. C'est economiquement absurde, surtout si ADN n'a pas d'actifs a saisir. La menace d'arbitrage de CC est probablement du bluff.`,
    keywords: ["clause 14", "arbitration", "icc", "geneve", "suisse", "anglais", "cout", "80000", "300000"]
  }
];

export default clausesCompletesChunks;
